<template>
  <div class="about">
    <div class="container">
      <img
        src="../../assets/gradient-top-yellow.png"
        class="app__gradient-top-yellow"
      />
      <img
        src="../../assets/gradient-top-blue.png"
        class="app__gradient-top-blue"
      />
      <AppHeader current-page="about"><AppMenu /></AppHeader>

      <div class="jumbotron">
        <div class="hex">
          <img src="../../assets/pattern-hex.png" alt="" />
        </div>
        <div class="title">About</div>
        <div class="description">
          In Causal Foundry, we research and build software that delivers
          adaptive interventions based on data generated by digital devices and
          applications, clinical records, gene expression data, and sequencing
          and profiling of biological samples. We provide an adaptive
          experimentation platform that enables new experimental approaches to
          design and analyze sequential, single- or multiple-assignment
          interventions.
        </div>
        <div class="description">
          Our work at Causal Foundry involves leveraging behavioral and clinical
          data from digital health solutions, along with other relevant
          contextual information. This approach allows us to provide adaptive
          interventions to a wide range of healthcare professionals and their
          patients. These interventions are distributed directly through digital
          tools as personalized recommendations, reminders, incentives, or
          integrated content and workflows within the app. Our goal is to ensure
          that each intervention is not just effective but also specifically
          tailored to the needs and circumstances of each recipient, enhancing
          the overall healthcare experience
        </div>
      </div>

      <div class="team">
        <div class="title">Our team</div>
        <div class="members">
          <div v-for="member of team" class="member">
            <div class="avatar">
              <img :src="getImageUrl(member.imageUrl)" alt="" />
              <div class="description">{{ member.descritpion }}</div>
            </div>
            <div class="info">
              <div class="name">{{ member.name }}</div>
              <div class="role">{{ member.role }}</div>
              <div class="links">
                <a
                  v-if="member.links.linkedin"
                  :href="member.links.linkedin"
                  target="_blank"
                >
                  <img
                    src="../../assets/linkedin-about.png"
                    class="link linkedin"
                  />
                </a>
                <a
                  v-if="member.links.twitter"
                  :href="member.links.twitter"
                  target="_blank"
                >
                  <img
                    src="../../assets/twitter-about.png"
                    class="link twitter"
                  />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <AppFooter />

      <img
        src="../../assets/gradient-bottom-yellow.png"
        class="app__gradient-bottom-yellow"
      />
      <img
        src="../../assets/gradient-bottom-blue.png"
        class="app__gradient-bottom-blue"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import AppHeader from "@/components/AppHeader";
import AppMenu from "@/components/AppMenu";
import AppFooter from "@/components/AppFooter";

import "./About.scss";

function getImageUrl(url: string) {
  return new URL(url, import.meta.url).href;
}

const team = [
  {
    imageUrl: "../../assets/africa.png",
    name: "África Periáñez",
    role: "CEO & Founder",
    descritpion: `África Periáñez, CEO and co-founder of Causal Foundry, is an AI entrepreneur dedicated to addressing health inequalities in low- and middle-income countries using data and machine learning. With a Ph.D. in Mathematics and extensive experience, including roles at Inditex and founding benshi.ai and Yokozuna Data, she leads the development of AI products tailored for healthcare professionals and patients. África's expertise spans from academia to industry, with a focus on personalized interventions and robust data collection to drive positive change.`,
    links: {
      linkedin: "https://linkedin.com",
      twitter: "https://twitter.com",
    },
  },
  {
    imageUrl: "../../assets/dexian.png",
    name: "Dexian Tang",
    role: "CTO & Co-Founder",
    descritpion: `África Periáñez, CEO and co-founder of Causal Foundry, is an AI entrepreneur dedicated to addressing health inequalities in low- and middle-income countries using data and machine learning. With a Ph.D. in Mathematics and extensive experience, including roles at Inditex and founding benshi.ai and Yokozuna Data, she leads the development of AI products tailored for healthcare professionals and patients. África's expertise spans from academia to industry, with a focus on personalized interventions and robust data collection to drive positive change.`,
    links: {
      twitter: "https://twitter.com",
    },
  },
  {
    imageUrl: "../../assets/africa.png",
    name: "Sumiko Tanaka Pusch",
    role: "COO",
    descritpion: `Sumiko is the COO at Causal Foundry. She brings extensive experience in working globally with international institutions, nonprofit organizations, and corporate businesses. Her focus includes ensuring the effective implementation of projects and programs, and the successful management of partnerships. She holds a BA in International Relations from the University of Washington and a dual master’s degree in strategic negotiations at Paris-Sud University..`,
    links: {
      linkedin: "https://linkedin.com",
    },
  },
  {
    imageUrl: "../../assets/enric.png",
    name: "Enric Jané",
    role: "CSO",
    descritpion: `África Periáñez, CEO and co-founder of Causal Foundry, is an AI entrepreneur dedicated to addressing health inequalities in low- and middle-income countries using data and machine learning. With a Ph.D. in Mathematics and extensive experience, including roles at Inditex and founding benshi.ai and Yokozuna Data, she leads the development of AI products tailored for healthcare professionals and patients. África's expertise spans from academia to industry, with a focus on personalized interventions and robust data collection to drive positive change.`,
    links: {
      linkedin: "https://linkedin.com",
    },
  },
  {
    imageUrl: "../../assets/africa.png",
    name: "Ana Fernández del Río",
    role: "Principal Data Scientist",
    descritpion: `África Periáñez, CEO and co-founder of Causal Foundry, is an AI entrepreneur dedicated to addressing health inequalities in low- and middle-income countries using data and machine learning. With a Ph.D. in Mathematics and extensive experience, including roles at Inditex and founding benshi.ai and Yokozuna Data, she leads the development of AI products tailored for healthcare professionals and patients. África's expertise spans from academia to industry, with a focus on personalized interventions and robust data collection to drive positive change.`,
    links: {
      linkedin: "https://linkedin.com",
    },
  },
  {
    imageUrl: "../../assets/ruth.png",
    name: "Ruth Barry",
    role: "Operations Manager",
    descritpion: `África Periáñez, CEO and co-founder of Causal Foundry, is an AI entrepreneur dedicated to addressing health inequalities in low- and middle-income countries using data and machine learning. With a Ph.D. in Mathematics and extensive experience, including roles at Inditex and founding benshi.ai and Yokozuna Data, she leads the development of AI products tailored for healthcare professionals and patients. África's expertise spans from academia to industry, with a focus on personalized interventions and robust data collection to drive positive change.`,
    links: {
      linkedin: "https://linkedin.com",
    },
  },
];
</script>
