<template>
  <div class="about">
    <div class="container">
      <img
        src="../../assets/gradient-top-yellow.png"
        class="app__gradient-top-yellow"
      />
      <img
        src="../../assets/gradient-top-blue.png"
        class="app__gradient-top-blue"
      />
      <AppHeader current-page="about"><AppMenu /></AppHeader>

      <div class="jumbotron">
        <div class="hex">
          <img src="../../assets/pattern-hex.png" alt="" />
        </div>
        <div class="title">
          On a Mission to <br /><AppTitle>Deliver AI for All</AppTitle>
        </div>
        <div class="description">
          We are a public benefit corporation that researches and builds AI
          software. Our platform and models predict clinical and behavioral
          outcomes and deliver adaptive interventions based on data generated by
          digital devices, clinical records, and profiling of biological
          samples, along with other contextual information. These interventions
          are distributed directly to patients and providers through digital
          tools such as personalized recommendations, reminders, incentives, or
          integrated content and workflows within the applications. Our goal is
          to ensure that each intervention is not just effective but also
          specifically tailored to the needs and circumstances of each recipient
        </div>
      </div>

      <div class="team">
        <div class="title">Our team</div>
        <div class="members">
          <div v-for="member of team" class="member">
            <div class="avatar">
              <img :src="member.imageUrl" alt="" />
              <div class="description">{{ member.descritpion }}</div>
            </div>
            <div class="info">
              <div class="name">{{ member.name }}</div>
              <div class="role">{{ member.role }}</div>
              <div class="links">
                <a
                  v-if="member.links.linkedin"
                  :href="member.links.linkedin"
                  target="_blank"
                >
                  <img
                    src="../../assets/linkedin-about.png"
                    class="link linkedin"
                  />
                </a>
                <a
                  v-if="member.links.twitter"
                  :href="member.links.twitter"
                  target="_blank"
                >
                  <img
                    src="../../assets/twitter-about.png"
                    class="link twitter"
                  />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <AppFooter />

      <img
        src="../../assets/gradient-bottom-yellow.png"
        class="app__gradient-bottom-yellow"
      />
      <img
        src="../../assets/gradient-bottom-blue.png"
        class="app__gradient-bottom-blue"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import AppHeader from "@/components/AppHeader";
import AppMenu from "@/components/AppMenu";
import AppFooter from "@/components/AppFooter";
import AppTitle from "@/components/AppTitle";

import team from "@/data/team";

import "./About.scss";
</script>
