export const ABOUT_DESCRIPTION = `
We are a public benefit corporation with a mission 
to scale Reinforcement Learning and advanced AI technology.
\n
Built on our own research and engineering, our platform 
and scientists use models to predict clinical and 
behavioral outcomes and deliver adaptive interventions 
based on data generated by digital applications and devices 
along with other contextual information. These interventions 
are distributed directly to users through digital tools such as 
personalized recommendations, reminders, incentives, 
or integrated content and workflows within the applications.
\n
Our goal is to ensure that each intervention is not just effective but
also specifically tailored to the needs and circumstances of each
user.`;

export const ABOUT_TITLE = `
We are a public benefit corporation with a mission to scale
Reinforcement Learning and advanced AI technology.`;

export const values = [
  {
    title: "Honesty",
    text: "We value transparency and integrity, ensuring open communication and trust as the foundation of our collaboration",
  },
  {
    title: "Focused & Fast-Paced",
    text: "Our work culture prioritizes precision, intensity, and speed, enabling us to develop cutting-edge technology with unmatched rigor",
  },
  {
    title: "Innovative Collaboration",
    text: "By blending individual responsibility with team synergy, we create a dynamic environment where top talent pushes the boundaries of AI innovation",
  },
  {
    title: "High-Performance",
    text: "We foster a culture where only the most effective individuals thrive, delivering results that drive meaningful impact",
  },
];

export const MISSION = `
We believe in tailored solutions over one-size-fits-all approaches. 
Our AI products deliver personalized strategies adapted to individual
preferences, environments, and behaviors, empowering organizations
to achieve exceptional outcomes. Committed to democratizing AI and
reinforcement learning, we make transformative technology accessible
to everyone, driving innovation and delivering personalized success at scale`;
