export const ABOUT_DESCRIPTION = `
Built on our own research and engineering, our platform and scientists
use models to predict clinical and behavioral outcomes and deliver
adaptive interventions based on data generated by digital applications
and devices along with other contextual information. These
interventions are distributed directly to users through digital tools
such as personalized recommendations, reminders, incentives, or
integrated content and workflows within the applications.
\n\n
Our goal is to ensure that each intervention is not just effective but
also specifically tailored to the needs and circumstances of each
user.`;

export const ABOUT_TITLE = `
We are a public benefit corporation with a mission to scale
Reinforcement Learning and advanced AI technology.`;
